# Generated by Django 3.1.2 on 2020-11-11 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=40, verbose_name='Имя')),
                ('status', models.CharField(choices=[('b', 'buyer'), ('s', 'seller')], help_text='Статус', max_length=1, verbose_name='Статус')),
                ('rating', models.FloatField(help_text='Рейтинг', verbose_name='Рейтинг')),
                ('bio', models.CharField(help_text='Краткая информация', max_length=200, verbose_name='Краткая информация')),
                ('about', models.TextField(help_text='Информация о профиле', verbose_name='Информация о профиле')),
                ('follows', models.ManyToManyField(help_text='Подписки', related_name='followers', to='frick_stock_api.Client', verbose_name='Подписки')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_photo', models.ImageField(help_text='Большая фотография', upload_to='', verbose_name='Большая фотография')),
                ('little_photo', models.ImageField(help_text='Маленькая фотография', upload_to='', verbose_name='Маленькая фотография')),
                ('header_photo', models.ImageField(help_text='Фотография шапки', upload_to='', verbose_name='Фотография шапки')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed', models.FloatField(help_text='Нужно денег', verbose_name='Нужно денег')),
                ('has', models.FloatField(help_text='Имеется денег', verbose_name='Имеется денег')),
                ('kind', models.CharField(choices=[('f', 'fast'), ('l', 'long')], help_text='Вид оплаты', max_length=1, verbose_name='Вид оплаты')),
                ('donators', models.ManyToManyField(help_text='Донатеры', related_name='donated', to='frick_stock_api.Client', verbose_name='Донатеры')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название лота', max_length=100, verbose_name='Название лота')),
                ('description', models.TextField(help_text='Описание лота', verbose_name='Описание лота')),
                ('buyer', models.ForeignKey(help_text='Покупатели лота', on_delete=django.db.models.deletion.CASCADE, related_name='lots_bought', to='frick_stock_api.client', verbose_name='Покупатели лота')),
                ('likes', models.ManyToManyField(help_text='Лайкнули', related_name='liked', to='frick_stock_api.Client', verbose_name='Лайкнули')),
                ('media', models.OneToOneField(help_text='Фотографии', on_delete=django.db.models.deletion.CASCADE, to='frick_stock_api.photos', verbose_name='Фотографии')),
                ('owner', models.OneToOneField(help_text='Владец лота', on_delete=django.db.models.deletion.CASCADE, to='frick_stock_api.client', verbose_name='Владелец лота')),
                ('price', models.OneToOneField(help_text='Цена', on_delete=django.db.models.deletion.CASCADE, to='frick_stock_api.price', verbose_name='Цена')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='photos',
            field=models.OneToOneField(help_text='Фотографии', on_delete=django.db.models.deletion.CASCADE, to='frick_stock_api.photos', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
