# Generated by Django 3.1.2 on 2020-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frick_stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='follows',
            field=models.ManyToManyField(blank=True, help_text='Подписки', related_name='followers', to='frick_stock_api.Client', verbose_name='Подписки'),
        ),
    ]
