# Generated by Django 3.1.2 on 2020-11-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frick_stock_api', '0002_auto_20201122_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photos',
            field=models.OneToOneField(blank=True, help_text='Фотографии', on_delete=django.db.models.deletion.CASCADE, to='frick_stock_api.photos', verbose_name='Фотографии'),
        ),
    ]
