# Generated by Django 3.1.2 on 2020-11-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frick_stock_api', '0005_auto_20201122_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Куплю'), ('s', 'Продам')], help_text='Статус лота', max_length=1, null=True, verbose_name='Статус лота'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, help_text='Статус', max_length=80, null=True, verbose_name='Статус'),
        ),
    ]
