# Generated by Django 3.1.2 on 2021-01-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frick_stock_api', '0006_auto_20201128_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.FloatField(blank=True, help_text='Баланс', max_length=3, null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.TextField(blank=True, help_text='Город', null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='owner',
            field=models.ForeignKey(help_text='Владец лота', on_delete=django.db.models.deletion.CASCADE, to='frick_stock_api.client', verbose_name='Владелец лота'),
        ),
    ]
